cmake_minimum_required(VERSION 3.16)
project(GST_PLUGIN_QTI_OSS_JPEGPACKER
  VERSION ${GST_PLUGINS_QTI_OSS_VERSION}
  LANGUAGES C
)

find_package(PkgConfig)

# Get the pkgconfigs exported by the automake tools
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH ON)
set(CMAKE_PREFIX_PATH "${PKG_CONFIG_LOCAL_PATH}")

pkg_check_modules(GST REQUIRED gstreamer-1.0>=${GST_VERSION_REQUIRED})
pkg_check_modules(GST_BASE REQUIRED gstreamer-base-1.0>=${GST_VERSION_REQUIRED})

# Generate configuration header file with plugin describing definitions
configure_file(config.h.in config.h @ONLY)
include_directories(${CMAKE_CURRENT_BINARY_DIR})

# Precompiler definitions.
add_definitions(-DHAVE_CONFIG_H)

# Common compiler flags.
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Werror")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-parameter")

set(JPEG_PACKER gstqtijpegpacker)

add_library(${JPEG_PACKER} SHARED
  jpegpacker-utils.c
  jpegpacker.c
)

target_include_directories(${JPEG_PACKER} PRIVATE
  ${GST_INCLUDE_DIRS}
)

target_link_libraries(${JPEG_PACKER} PUBLIC
  ${GST_LIBRARIES}
  ${GST_BASE_LIBRARIES}
  gstqtiutilsbase
  exif
)

install(
  TARGETS ${JPEG_PACKER}
  LIBRARY DESTINATION ${GST_PLUGINS_QTI_OSS_INSTALL_LIBDIR}/gstreamer-1.0
  PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
              GROUP_EXECUTE GROUP_READ
              WORLD_EXECUTE WORLD_READ
)
