usr/lib/${DEB_HOST_MULTIARCH}/libgstqtiallocatorsbase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqticvbase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqtimemorybase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqtivideobase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqtimlbase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqtiutilsbase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqtigfxbase.so.*
usr/lib/${DEB_HOST_MULTIARCH}/libgstqticamerabase.so.*
